### ISSUE TITLE
Tuesday 17-09-2024 : Roll call 

### ISSUE THREAD

**Issue by sammou00** [BF-backEnd-class-2024/home#16]
## Roll Call!

Leave a comment with these two things:

1. A summary of your study using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by rodicailciuc** [comment]
Good morning!

**Comment by richellepintucan** [comment]
Hello, good morning

**Comment by emrahhko** [comment]
Günaydin !

**Comment by SowmyaPuttaswamygowda** [comment]
Hello, gm.

**Comment by Adileljihad** [comment]
Good morning.

**Comment by sri12334** [comment]
good morning

**Comment by Agnieszka-Dzwolak** [comment]
hi

**Comment by ahlamboudali** [comment]
Good Morning

**Comment by egidehirwa** [comment]
Bien le bonjour !

**Comment by enteryana** [comment]
Hi

**Comment by rohma19** [comment]
morning

**Comment by minjupgeorge** [comment]
Good Morning
:)

**Comment by dspodina** [comment]
Good morning!

**Comment by gultekinbirol** [comment]
Hello

**Comment by MassimilianoMarcello** [comment]
hello

**Comment by xamwell2** [comment]
👋👋
