### ISSUE TITLE
Monday 21-10-2024 roll call 

### ISSUE THREAD

**Issue by sammou00** [BF-backEnd-class-2024/home#196]
## Roll Call!

Leave a comment with these two things:

1. A summary of your study using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by SowmyaPuttaswamygowda** [comment]
Hello GM!

**Comment by MassimilianoMarcello** [comment]
Good morning

**Comment by gultekinbirol** [comment]
Gm

**Comment by sri12334** [comment]
good morning

**Comment by emrahhko** [comment]
bonjour

**Comment by rodicailciuc** [comment]
morning!

**Comment by Adileljihad** [comment]
hello

**Comment by ahlamboudali** [comment]
Good Morning

**Comment by Agnieszka-Dzwolak** [comment]
hi

**Comment by rohma19** [comment]
good morning

**Comment by richellepintucan** [comment]
Hi

**Comment by egidehirwa** [comment]
Bien le bonjour !

**Comment by enteryana** [comment]
hi hi

**Comment by xamwell2** [comment]
Hello GM!
